name: uses-sentinel
description: A GitHub Action that checks if any action in your workflows uses unsafe versions or outdated actions.
author: Maor Kavod
branding:
  icon: alert-circle
  color: red

inputs:
  exlude:
    description: 'A list of actions paths to exclude from the check'
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'docker://bash:latest'
  entrypoint: 'sh'
  env:
    EXCLUDE: ${{ inputs.exlude }}
  args:
    - '-c'
    - './entrypoint.sh'
